name: Node.js CI

on:
  push:
    branches: [ "principal" ]
  pull_request:
    branches: [ "principal" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Instalar Dependências
      run: npm install
      
    - name: Executar Testes
      run: npm test --if-present
